-- new object type path is: SCHEMA_EXPORT/TABLE/TABLE
CREATE TABLE "SH"."CHANNELS" 
   (	"CHANNEL_ID" NUMBER NOT NULL ENABLE, 
	"CHANNEL_DESC" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CHANNEL_CLASS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CHANNEL_CLASS_ID" NUMBER NOT NULL ENABLE, 
	"CHANNEL_TOTAL" VARCHAR2(13 BYTE) NOT NULL ENABLE, 
	"CHANNEL_TOTAL_ID" NUMBER NOT NULL ENABLE
   ) ;
 
CREATE TABLE "SH"."COUNTRIES" 
   (	"COUNTRY_ID" NUMBER NOT NULL ENABLE, 
	"COUNTRY_ISO_CODE" CHAR(2 BYTE) NOT NULL ENABLE, 
	"COUNTRY_NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"COUNTRY_SUBREGION" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"COUNTRY_SUBREGION_ID" NUMBER NOT NULL ENABLE, 
	"COUNTRY_REGION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"COUNTRY_REGION_ID" NUMBER NOT NULL ENABLE, 
	"COUNTRY_TOTAL" VARCHAR2(11 BYTE) NOT NULL ENABLE, 
	"COUNTRY_TOTAL_ID" NUMBER NOT NULL ENABLE, 
	"COUNTRY_NAME_HIST" VARCHAR2(40 BYTE)
   ) ;
 
CREATE TABLE "SH"."CUSTOMERS" 
   (	"CUST_ID" NUMBER NOT NULL ENABLE, 
	"CUST_FIRST_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CUST_LAST_NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CUST_GENDER" CHAR(1 BYTE) NOT NULL ENABLE, 
	"CUST_YEAR_OF_BIRTH" NUMBER(4,0) NOT NULL ENABLE, 
	"CUST_MARITAL_STATUS" VARCHAR2(20 BYTE), 
	"CUST_STREET_ADDRESS" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CUST_POSTAL_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"CUST_CITY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CUST_CITY_ID" NUMBER NOT NULL ENABLE, 
	"CUST_STATE_PROVINCE" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CUST_STATE_PROVINCE_ID" NUMBER NOT NULL ENABLE, 
	"COUNTRY_ID" NUMBER NOT NULL ENABLE, 
	"CUST_MAIN_PHONE_NUMBER" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"CUST_INCOME_LEVEL" VARCHAR2(30 BYTE), 
	"CUST_CREDIT_LIMIT" NUMBER, 
	"CUST_EMAIL" VARCHAR2(50 BYTE), 
	"CUST_TOTAL" VARCHAR2(14 BYTE) NOT NULL ENABLE, 
	"CUST_TOTAL_ID" NUMBER NOT NULL ENABLE, 
	"CUST_SRC_ID" NUMBER, 
	"CUST_EFF_FROM" DATE, 
	"CUST_EFF_TO" DATE, 
	"CUST_VALID" VARCHAR2(1 BYTE)
   ) ;
 
CREATE TABLE "SH"."PROMOTIONS" 
   (	"PROMO_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"PROMO_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PROMO_SUBCATEGORY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PROMO_SUBCATEGORY_ID" NUMBER NOT NULL ENABLE, 
	"PROMO_CATEGORY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PROMO_CATEGORY_ID" NUMBER NOT NULL ENABLE, 
	"PROMO_COST" NUMBER(10,2) NOT NULL ENABLE, 
	"PROMO_BEGIN_DATE" DATE NOT NULL ENABLE, 
	"PROMO_END_DATE" DATE NOT NULL ENABLE, 
	"PROMO_TOTAL" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"PROMO_TOTAL_ID" NUMBER NOT NULL ENABLE
   ) ;
 
CREATE TABLE "SH"."PRODUCTS" 
   (	"PROD_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"PROD_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PROD_DESC" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"PROD_SUBCATEGORY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PROD_SUBCATEGORY_ID" NUMBER NOT NULL ENABLE, 
	"PROD_SUBCATEGORY_DESC" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"PROD_CATEGORY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PROD_CATEGORY_ID" NUMBER NOT NULL ENABLE, 
	"PROD_CATEGORY_DESC" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"PROD_WEIGHT_CLASS" NUMBER(3,0) NOT NULL ENABLE, 
	"PROD_UNIT_OF_MEASURE" VARCHAR2(20 BYTE), 
	"PROD_PACK_SIZE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"SUPPLIER_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"PROD_STATUS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROD_LIST_PRICE" NUMBER(8,2) NOT NULL ENABLE, 
	"PROD_MIN_PRICE" NUMBER(8,2) NOT NULL ENABLE, 
	"PROD_TOTAL" VARCHAR2(13 BYTE) NOT NULL ENABLE, 
	"PROD_TOTAL_ID" NUMBER NOT NULL ENABLE, 
	"PROD_SRC_ID" NUMBER, 
	"PROD_EFF_FROM" DATE, 
	"PROD_EFF_TO" DATE, 
	"PROD_VALID" VARCHAR2(1 BYTE)
   ) ;
 
CREATE TABLE "SH"."SUPPLEMENTARY_DEMOGRAPHICS" 
   (	"CUST_ID" NUMBER NOT NULL ENABLE, 
	"EDUCATION" VARCHAR2(21 BYTE), 
	"OCCUPATION" VARCHAR2(21 BYTE), 
	"HOUSEHOLD_SIZE" VARCHAR2(21 BYTE), 
	"YRS_RESIDENCE" NUMBER, 
	"AFFINITY_CARD" NUMBER(10,0), 
	"BULK_PACK_DISKETTES" NUMBER(10,0), 
	"FLAT_PANEL_MONITOR" NUMBER(10,0), 
	"HOME_THEATER_PACKAGE" NUMBER(10,0), 
	"BOOKKEEPING_APPLICATION" NUMBER(10,0), 
	"PRINTER_SUPPLIES" NUMBER(10,0), 
	"Y_BOX_GAMES" NUMBER(10,0), 
	"OS_DOC_SET_KANJI" NUMBER(10,0), 
	"COMMENTS" VARCHAR2(4000 BYTE)
   ) ;
 
CREATE TABLE "SH"."SALES" 
   (	"PROD_ID" NUMBER NOT NULL ENABLE, 
	"CUST_ID" NUMBER NOT NULL ENABLE, 
	"TIME_ID" DATE NOT NULL ENABLE, 
	"CHANNEL_ID" NUMBER NOT NULL ENABLE, 
	"PROMO_ID" NUMBER NOT NULL ENABLE, 
	"QUANTITY_SOLD" NUMBER(10,2) NOT NULL ENABLE, 
	"SELLER" NUMBER(6,0) NOT NULL ENABLE, 
	"FULFILLMENT_CENTER" NUMBER(6,0) NOT NULL ENABLE, 
	"COURIER_ORG" NUMBER(6,0) NOT NULL ENABLE, 
	"TAX_COUNTRY" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"TAX_REGION" VARCHAR2(3 BYTE), 
	"AMOUNT_SOLD" NUMBER(10,2) NOT NULL ENABLE
   ) ;
 
CREATE TABLE "SH"."TIMES" 
   (	"TIME_ID" DATE, 
	"DAY_NAME" VARCHAR2(9 BYTE), 
	"DAY_NUMBER_IN_MONTH" VARCHAR2(2 BYTE), 
	"DAY_NUMBER_IN_YEAR" VARCHAR2(3 BYTE), 
	"CALENDAR_YEAR" VARCHAR2(4 BYTE), 
	"CALENDAR_QUARTER_NUMBER" VARCHAR2(1 BYTE), 
	"CALENDAR_MONTH_NUMBER" VARCHAR2(2 BYTE), 
	"CALENDAR_WEEK_NUMBER" VARCHAR2(2 BYTE), 
	"CALENDAR_MONTH_DESC" VARCHAR2(7 BYTE), 
	"CALENDAR_QUARTER_DESC" VARCHAR2(6 BYTE)
   ) ;
 
CREATE TABLE "SOE"."CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER(12,0) CONSTRAINT "CUST_CUSTID_NN" NOT NULL ENABLE, 
	"CUST_FIRST_NAME" VARCHAR2(40 BYTE) CONSTRAINT "CUST_FNAME_NN" NOT NULL ENABLE, 
	"CUST_LAST_NAME" VARCHAR2(40 BYTE) CONSTRAINT "CUST_LNAME_NN" NOT NULL ENABLE, 
	"NLS_LANGUAGE" VARCHAR2(3 BYTE), 
	"NLS_TERRITORY" VARCHAR2(90 BYTE), 
	"CREDIT_LIMIT" NUMBER(9,2), 
	"CUST_EMAIL" VARCHAR2(100 BYTE), 
	"ACCOUNT_MGR_ID" NUMBER(12,0), 
	"CUSTOMER_SINCE" DATE, 
	"CUSTOMER_CLASS" VARCHAR2(40 BYTE), 
	"SUGGESTIONS" VARCHAR2(40 BYTE), 
	"DOB" DATE, 
	"MAILSHOT" VARCHAR2(1 BYTE), 
	"PARTNER_MAILSHOT" VARCHAR2(1 BYTE), 
	"PREFERRED_ADDRESS" NUMBER(12,0), 
	"PREFERRED_CARD" NUMBER(12,0)
   ) ;
 
CREATE TABLE "SOE"."ADDRESSES" 
   (	"ADDRESS_ID" NUMBER(12,0) CONSTRAINT "ADDRESS_ID_NN" NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER(12,0) CONSTRAINT "ADDRESS_CUST_ID_NN" NOT NULL ENABLE, 
	"DATE_CREATED" DATE CONSTRAINT "ADDRESS_DATEC_NN" NOT NULL ENABLE, 
	"HOUSE_NO_OR_NAME" VARCHAR2(60 BYTE), 
	"STREET_NAME" VARCHAR2(60 BYTE), 
	"TOWN" VARCHAR2(60 BYTE), 
	"COUNTY" VARCHAR2(60 BYTE), 
	"COUNTRY" VARCHAR2(60 BYTE), 
	"POST_CODE" VARCHAR2(12 BYTE), 
	"ZIP_CODE" VARCHAR2(12 BYTE)
   ) ;
 
CREATE TABLE "SOE"."CARD_DETAILS" 
   (	"CARD_ID" NUMBER(12,0) CONSTRAINT "CARD_ID_NN" NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER(12,0) CONSTRAINT "CARD_CUST_ID_NN" NOT NULL ENABLE, 
	"CARD_TYPE" VARCHAR2(60 BYTE) CONSTRAINT "CARD_TYPE_NN" NOT NULL ENABLE, 
	"CARD_NUMBER" NUMBER(12,0) CONSTRAINT "CARD_NUMBER_NN" NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE CONSTRAINT "EXPIRY_DATE_NN" NOT NULL ENABLE, 
	"IS_VALID" VARCHAR2(30 BYTE) CONSTRAINT "IS_VALID_NN" NOT NULL ENABLE, 
	"SECURITY_CODE" NUMBER(6,0)
   ) ;
 
CREATE TABLE "SOE"."WAREHOUSES" 
   (	"WAREHOUSE_ID" NUMBER(6,0), 
	"WAREHOUSE_NAME" VARCHAR2(35 BYTE), 
	"LOCATION_ID" NUMBER(4,0)
   ) ;
 
CREATE TABLE "SOE"."ORDER_ITEMS" 
   (	"ORDER_ID" NUMBER(12,0) CONSTRAINT "OI_ORDER_ID_NN" NOT NULL ENABLE, 
	"LINE_ITEM_ID" NUMBER(3,0) CONSTRAINT "OI_LINEITEM_ID_NN" NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(6,0) CONSTRAINT "OI_PRODUCT_ID_NN" NOT NULL ENABLE, 
	"UNIT_PRICE" NUMBER(8,2), 
	"QUANTITY" NUMBER(8,0), 
	"DISPATCH_DATE" DATE, 
	"RETURN_DATE" DATE, 
	"GIFT_WRAP" VARCHAR2(45 BYTE), 
	"CONDITION" VARCHAR2(45 BYTE), 
	"SUPPLIER_ID" NUMBER(6,0), 
	"ESTIMATED_DELIVERY" DATE
   ) ;
 
CREATE TABLE "SOE"."ORDERS" 
   (	"ORDER_ID" NUMBER(12,0) CONSTRAINT "ORDER_ORDER_ID_NN" NOT NULL ENABLE, 
	"ORDER_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE CONSTRAINT "ORDER_DATE_NN" NOT NULL ENABLE, 
	"ORDER_MODE" VARCHAR2(8 BYTE), 
	"CUSTOMER_ID" NUMBER(12,0) CONSTRAINT "ORDER_CUSTOMER_ID_NN" NOT NULL ENABLE, 
	"ORDER_STATUS" NUMBER(2,0), 
	"ORDER_TOTAL" NUMBER(10,2), 
	"SALES_REP_ID" NUMBER(6,0), 
	"PROMOTION_ID" NUMBER(6,0), 
	"WAREHOUSE_ID" NUMBER(6,0), 
	"DELIVERY_TYPE" VARCHAR2(60 BYTE), 
	"COST_OF_DELIVERY" NUMBER(6,0), 
	"WAIT_TILL_ALL_AVAILABLE" VARCHAR2(60 BYTE), 
	"DELIVERY_ADDRESS_ID" NUMBER(12,0), 
	"CUSTOMER_CLASS" VARCHAR2(60 BYTE), 
	"CARD_ID" NUMBER(12,0), 
	"INVOICE_ADDRESS_ID" NUMBER(12,0)
   ) ;
 
CREATE TABLE "SOE"."INVENTORIES" 
   (	"PRODUCT_ID" NUMBER(6,0) CONSTRAINT "INVENTORY_PROODUCT_ID_NN" NOT NULL ENABLE, 
	"WAREHOUSE_ID" NUMBER(6,0) CONSTRAINT "INVENTORY_WAREHOUSE_ID_NN" NOT NULL ENABLE, 
	"QUANTITY_ON_HAND" NUMBER(8,0) CONSTRAINT "INVENTORY_QOH_NN" NOT NULL ENABLE
   ) ;
 
CREATE TABLE "SOE"."PRODUCT_INFORMATION" 
   (	"PRODUCT_ID" NUMBER(6,0) CONSTRAINT "PRODUCT_PRODUCT_ID_NN" NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(50 BYTE) CONSTRAINT "PRODUCT_PRODUCT_NAME_NN" NOT NULL ENABLE, 
	"PRODUCT_DESCRIPTION" VARCHAR2(2000 BYTE), 
	"CATEGORY_ID" NUMBER(4,0) CONSTRAINT "PRODUCT_CATEGORY_ID_NN" NOT NULL ENABLE, 
	"WEIGHT_CLASS" NUMBER(1,0), 
	"WARRANTY_PERIOD" INTERVAL YEAR (2) TO MONTH, 
	"SUPPLIER_ID" NUMBER(6,0), 
	"PRODUCT_STATUS" VARCHAR2(20 BYTE), 
	"LIST_PRICE" NUMBER(8,2), 
	"MIN_PRICE" NUMBER(8,2), 
	"CATALOG_URL" VARCHAR2(50 BYTE)
   ) ;
 
CREATE TABLE "SOE"."LOGON" 
   (	"LOGON_ID" NUMBER CONSTRAINT "LOGON_LOGON_ID_NN" NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER CONSTRAINT "LOGON_CUSTOMER_ID_NN" NOT NULL ENABLE, 
	"LOGON_DATE" DATE
   ) ;
 
CREATE TABLE "SOE"."PRODUCT_DESCRIPTIONS" 
   (	"PRODUCT_ID" NUMBER(6,0), 
	"LANGUAGE_ID" VARCHAR2(3 BYTE), 
	"TRANSLATED_NAME" NVARCHAR2(50) CONSTRAINT "TRANSLATED_NAME_NN" NOT NULL ENABLE, 
	"TRANSLATED_DESCRIPTION" NVARCHAR2(2000) CONSTRAINT "TRANSLATED_DESC_NN" NOT NULL ENABLE
   ) ;
 
CREATE TABLE "SOE"."ORDERENTRY_METADATA" 
   (	"METADATA_KEY" VARCHAR2(30 BYTE), 
	"METADATA_VALUE" VARCHAR2(30 BYTE)
   ) ;
 
CREATE TABLE "MOVIE"."CUSTOMER_CONTACT" 
   (	"CUST_ID" NUMBER NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(200 BYTE), 
	"FIRST_NAME" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(500 BYTE), 
	"STREET_ADDRESS" VARCHAR2(400 BYTE), 
	"POSTAL_CODE" VARCHAR2(10 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"STATE_PROVINCE" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(400 BYTE), 
	"COUNTRY_CODE" VARCHAR2(2 BYTE), 
	"CONTINENT" VARCHAR2(400 BYTE), 
	"YRS_CUSTOMER" NUMBER, 
	"PROMOTION_RESPONSE" NUMBER, 
	"LOC_LAT" NUMBER, 
	"LOC_LONG" NUMBER
   ) ;
 
CREATE TABLE "MOVIE"."CUSTOMER_DEVICE" 
   (	"DEVICE_ID" NUMBER NOT NULL ENABLE, 
	"CUST_ID" NUMBER NOT NULL ENABLE, 
	"DEVICE_TYPE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DEVICE_MANUFACTURER" VARCHAR2(200 BYTE), 
	"DEVICE_OS" VARCHAR2(200 BYTE), 
	"DEVICE_VERSION" VARCHAR2(200 BYTE), 
	"INITIAL_ACCESS" TIMESTAMP (6), 
	"LAST_ACCESS" TIMESTAMP (6), 
	"ACCESS_COUNT" NUMBER
   ) ;
 
CREATE TABLE "MOVIE"."CUSTOMER_FRIENDS_AND_FAMILY" 
   (	"FRIEND_FAMILY_ID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_SOURCE" NUMBER, 
	"RELATIONSHIP" VARCHAR2(100 BYTE), 
	"CUSTOMER_TARGET" NUMBER
   ) ;
 
CREATE TABLE "MOVIE"."CUSTOMER_PAYMENT_INFORMATION" 
   (	"PAYMENT_INFORMATION_ID" NUMBER NOT NULL ENABLE, 
	"CUST_ID" NUMBER NOT NULL ENABLE, 
	"CARD_NUMBER" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PROVIDER" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"BILLING_STREET_ADDRESS" VARCHAR2(400 BYTE), 
	"BILLING_POSTAL_CODE" VARCHAR2(10 BYTE), 
	"BILLING_CITY" VARCHAR2(100 BYTE), 
	"BILLING_STATE_COUNTY" VARCHAR2(100 BYTE), 
	"BILLING_COUNTRY" VARCHAR2(400 BYTE), 
	"BILLING_COUNTRY_CODE" VARCHAR2(2 BYTE), 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"DEFAULT_PAYMENT_METHOD" CHAR(1 BYTE) NOT NULL ENABLE
   ) ;
 
CREATE TABLE "MOVIE"."CUSTOMER_REVIEW" 
   (	"CUST_ID" NUMBER NOT NULL ENABLE, 
	"MOVIE_ID" NUMBER NOT NULL ENABLE, 
	"STAR_RATING" NUMBER NOT NULL ENABLE, 
	"REVIEW" VARCHAR2(4000 BYTE), 
	"REVIEW_ID" NUMBER NOT NULL ENABLE, 
	"REVIEW_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE
   ) ;
 
CREATE TABLE "MOVIE"."INTERACTION" 
   (	"INTERACTION_ID" NUMBER NOT NULL ENABLE, 
	"CUST_ID" NUMBER NOT NULL ENABLE, 
	"INTERACTION_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"INTERACTION_TIME" TIMESTAMP (6) NOT NULL ENABLE
   ) ;
 
CREATE TABLE "MOVIE"."MOVIE_METADATA" 
   (	"METADATA_KEY" VARCHAR2(30 BYTE), 
	"METADATA_VALUE" VARCHAR2(30 BYTE)
   ) ;
 
CREATE TABLE "MOVIE"."MOVIE_DETAILS" 
   (	"MOVIE_ID" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(200 BYTE), 
	"BUDGET" NUMBER, 
	"GROSS" NUMBER, 
	"LIST_PRICE" NUMBER, 
	"SKU" VARCHAR2(30 BYTE), 
	"YEAR" NUMBER, 
	"OPENING_DATE" DATE, 
	"VIEWS" NUMBER, 
	"MAIN_SUBJECT" VARCHAR2(4000 BYTE), 
	"RUNTIME" NUMBER, 
	"SUMMARY" VARCHAR2(4000 BYTE)
   ) ;
 
CREATE TABLE "MOVIE"."CAST" 
   (	"CAST_ID" NUMBER NOT NULL ENABLE, 
	"CAST_NAME" VARCHAR2(200 BYTE), 
	"CAST_DOB" DATE
   ) ;
 
CREATE TABLE "MOVIE"."STUDIOS" 
   (	"STUDIO_ID" NUMBER NOT NULL ENABLE, 
	"STUDIO_NAME" VARCHAR2(200 BYTE)
   ) ;
 
CREATE TABLE "MOVIE"."AWARDS" 
   (	"AWARD_ID" NUMBER NOT NULL ENABLE, 
	"AWARD_NAME" VARCHAR2(200 BYTE)
   ) ;
 
CREATE TABLE "MOVIE"."NOMINATIONS" 
   (	"NOMINATION_ID" NUMBER NOT NULL ENABLE, 
	"NOMINATION_NAME" VARCHAR2(200 BYTE)
   ) ;
 
CREATE TABLE "MOVIE"."MOVIES_CAST_MAP" 
   (	"MOVIE_ID" NUMBER, 
	"CAST_ID" NUMBER
   ) ;
 
CREATE TABLE "MOVIE"."MOVIES_AWARD_MAP" 
   (	"MOVIE_ID" NUMBER, 
	"AWARDS_ID" NUMBER
   ) ;
 
CREATE TABLE "MOVIE"."CREW" 
   (	"CREW_ID" NUMBER NOT NULL ENABLE, 
	"CREW_NAME" VARCHAR2(200 BYTE)
   ) ;
 
CREATE TABLE "MOVIE"."MOVIES_CREW_MAP" 
   (	"MOVIE_ID" NUMBER, 
	"CREW_ID" NUMBER, 
	"CREW_ROLE" VARCHAR2(200 BYTE)
   ) ;
 
CREATE TABLE "MOVIE"."MOVIES_STUDIO_MAP" 
   (	"MOVIE_ID" NUMBER, 
	"STUDIO_ID" NUMBER
   ) ;
 
CREATE TABLE "MOVIE"."MOVIES_NOMINATION_MAP" 
   (	"MOVIE_ID" NUMBER, 
	"NOMINATION_ID" NUMBER
   ) ;
 
CREATE TABLE "TPCH"."NATION" 
   (	"N_NATIONKEY" NUMBER NOT NULL ENABLE, 
	"N_NAME" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"N_REGIONKEY" NUMBER NOT NULL ENABLE, 
	"N_COMMENT" VARCHAR2(152 BYTE)
   ) ;
 
CREATE TABLE "TPCH"."REGION" 
   (	"R_REGIONKEY" NUMBER NOT NULL ENABLE, 
	"R_NAME" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"R_COMMENT" VARCHAR2(152 BYTE)
   ) ;
 
CREATE TABLE "TPCH"."PART" 
   (	"P_PARTKEY" NUMBER NOT NULL ENABLE, 
	"P_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"P_MFGR" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"P_BRAND" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"P_TYPE" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"P_SIZE" NUMBER NOT NULL ENABLE, 
	"P_CONTAINER" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"P_RETAILPRICE" NUMBER(15,2) NOT NULL ENABLE, 
	"P_COMMENT" VARCHAR2(23 BYTE) NOT NULL ENABLE
   ) ;
 
CREATE TABLE "TPCH"."SUPPLIER" 
   (	"S_SUPPKEY" NUMBER NOT NULL ENABLE, 
	"S_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"S_ADDRESS" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"S_NATIONKEY" NUMBER NOT NULL ENABLE, 
	"S_PHONE" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"S_ACCTBAL" NUMBER(15,2) NOT NULL ENABLE, 
	"S_COMMENT" VARCHAR2(101 BYTE) NOT NULL ENABLE
   ) ;
 
CREATE TABLE "TPCH"."PARTSUPP" 
   (	"PS_PARTKEY" NUMBER NOT NULL ENABLE, 
	"PS_SUPPKEY" NUMBER NOT NULL ENABLE, 
	"PS_AVAILQTY" NUMBER NOT NULL ENABLE, 
	"PS_SUPPLYCOST" NUMBER(15,2) NOT NULL ENABLE, 
	"PS_COMMENT" VARCHAR2(199 BYTE) NOT NULL ENABLE
   ) ;
 
CREATE TABLE "TPCH"."CUSTOMER" 
   (	"C_CUSTKEY" NUMBER NOT NULL ENABLE, 
	"C_NAME" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"C_ADDRESS" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"C_NATIONKEY" NUMBER NOT NULL ENABLE, 
	"C_PHONE" CHAR(15 BYTE) NOT NULL ENABLE, 
	"C_ACCTBAL" NUMBER(15,2) NOT NULL ENABLE, 
	"C_MKTSEGMENT" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"C_COMMENT" VARCHAR2(117 BYTE) NOT NULL ENABLE
   ) ;
 
CREATE TABLE "TPCH"."ORDERS" 
   (	"O_ORDERKEY" NUMBER NOT NULL ENABLE, 
	"O_CUSTKEY" NUMBER NOT NULL ENABLE, 
	"O_ORDERSTATUS" CHAR(1 BYTE) NOT NULL ENABLE, 
	"O_TOTALPRICE" NUMBER(15,2) NOT NULL ENABLE, 
	"O_ORDERDATE" DATE NOT NULL ENABLE, 
	"O_ORDERPRIORITY" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"O_CLERK" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"O_SHIPPRIORITY" NUMBER NOT NULL ENABLE, 
	"O_COMMENT" VARCHAR2(79 BYTE) NOT NULL ENABLE
   ) ;
 
CREATE TABLE "TPCH"."LINEITEM" 
   (	"L_ORDERKEY" NUMBER NOT NULL ENABLE, 
	"L_PARTKEY" NUMBER NOT NULL ENABLE, 
	"L_SUPPKEY" NUMBER NOT NULL ENABLE, 
	"L_LINENUMBER" NUMBER NOT NULL ENABLE, 
	"L_QUANTITY" NUMBER(15,2) NOT NULL ENABLE, 
	"L_EXTENDEDPRICE" NUMBER(15,2) NOT NULL ENABLE, 
	"L_DISCOUNT" NUMBER(15,2) NOT NULL ENABLE, 
	"L_TAX" NUMBER(15,2) NOT NULL ENABLE, 
	"L_RETURNFLAG" CHAR(1 BYTE) NOT NULL ENABLE, 
	"L_LINESTATUS" CHAR(1 BYTE) NOT NULL ENABLE, 
	"L_SHIPDATE" DATE NOT NULL ENABLE, 
	"L_COMMITDATE" DATE NOT NULL ENABLE, 
	"L_RECEIPTDATE" DATE NOT NULL ENABLE, 
	"L_SHIPINSTRUCT" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"L_SHIPMODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"L_COMMENT" VARCHAR2(44 BYTE) NOT NULL ENABLE
   ) ;
 
CREATE TABLE "TPCDSLIKE"."CALL_CENTER" 
   (	"CC_CALL_CENTER_SK" NUMBER NOT NULL ENABLE, 
	"CC_CALL_CENTER_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"CC_REC_START_DATE" DATE, 
	"CC_REC_END_DATE" DATE, 
	"CC_CLOSED_DATE_SK" NUMBER, 
	"CC_OPEN_DATE_SK" NUMBER, 
	"CC_NAME" VARCHAR2(50 BYTE), 
	"CC_CLASS" VARCHAR2(50 BYTE), 
	"CC_EMPLOYEES" NUMBER, 
	"CC_SQ_FT" NUMBER, 
	"CC_HOURS" CHAR(20 BYTE), 
	"CC_MANAGER" VARCHAR2(40 BYTE), 
	"CC_MKT_ID" NUMBER, 
	"CC_MKT_CLASS" CHAR(50 BYTE), 
	"CC_MKT_DESC" VARCHAR2(100 BYTE), 
	"CC_MARKET_MANAGER" VARCHAR2(40 BYTE), 
	"CC_DIVISION" NUMBER, 
	"CC_DIVISION_NAME" VARCHAR2(50 BYTE), 
	"CC_COMPANY" NUMBER, 
	"CC_COMPANY_NAME" CHAR(50 BYTE), 
	"CC_STREET_NUMBER" CHAR(10 BYTE), 
	"CC_STREET_NAME" VARCHAR2(60 BYTE), 
	"CC_STREET_TYPE" CHAR(15 BYTE), 
	"CC_SUITE_NUMBER" CHAR(10 BYTE), 
	"CC_CITY" VARCHAR2(60 BYTE), 
	"CC_COUNTY" VARCHAR2(50 BYTE), 
	"CC_STATE" CHAR(2 BYTE), 
	"CC_ZIP" CHAR(10 BYTE), 
	"CC_COUNTRY" VARCHAR2(20 BYTE), 
	"CC_GMT_OFFSET" NUMBER(5,0), 
	"CC_TAX_PERCENTAGE" NUMBER(5,0)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."CATALOG_PAGE" 
   (	"CP_CATALOG_PAGE_SK" NUMBER NOT NULL ENABLE, 
	"CP_CATALOG_PAGE_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"CP_START_DATE_SK" NUMBER, 
	"CP_END_DATE_SK" NUMBER, 
	"CP_DEPARTMENT" VARCHAR2(50 BYTE), 
	"CP_CATALOG_NUMBER" NUMBER, 
	"CP_CATALOG_PAGE_NUMBER" NUMBER, 
	"CP_DESCRIPTION" VARCHAR2(100 BYTE), 
	"CP_TYPE" VARCHAR2(100 BYTE)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."CATALOG_RETURNS" 
   (	"CR_RETURNED_DATE_SK" NUMBER, 
	"CR_RETURNED_TIME_SK" NUMBER, 
	"CR_ITEM_SK" NUMBER NOT NULL ENABLE, 
	"CR_REFUNDED_CUSTOMER_SK" NUMBER, 
	"CR_REFUNDED_CDEMO_SK" NUMBER, 
	"CR_REFUNDED_HDEMO_SK" NUMBER, 
	"CR_REFUNDED_ADDR_SK" NUMBER, 
	"CR_RETURNING_CUSTOMER_SK" NUMBER, 
	"CR_RETURNING_CDEMO_SK" NUMBER, 
	"CR_RETURNING_HDEMO_SK" NUMBER, 
	"CR_RETURNING_ADDR_SK" NUMBER, 
	"CR_CALL_CENTER_SK" NUMBER, 
	"CR_CATALOG_PAGE_SK" NUMBER, 
	"CR_SHIP_MODE_SK" NUMBER, 
	"CR_WAREHOUSE_SK" NUMBER, 
	"CR_REASON_SK" NUMBER, 
	"CR_ORDER_NUMBER" NUMBER NOT NULL ENABLE, 
	"CR_RETURN_QUANTITY" NUMBER, 
	"CR_RETURN_AMOUNT" NUMBER(7,0), 
	"CR_RETURN_TAX" NUMBER(7,0), 
	"CR_RETURN_AMT_INC_TAX" NUMBER(7,0), 
	"CR_FEE" NUMBER(7,0), 
	"CR_RETURN_SHIP_COST" NUMBER(7,0), 
	"CR_REFUNDED_CASH" NUMBER(7,0), 
	"CR_REVERSED_CHARGE" NUMBER(7,0), 
	"CR_STORE_CREDIT" NUMBER(7,0), 
	"CR_NET_LOSS" NUMBER(7,0)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."CATALOG_SALES" 
   (	"CS_SOLD_DATE_SK" NUMBER, 
	"CS_SOLD_TIME_SK" NUMBER, 
	"CS_SHIP_DATE_SK" NUMBER, 
	"CS_BILL_CUSTOMER_SK" NUMBER, 
	"CS_BILL_CDEMO_SK" NUMBER, 
	"CS_BILL_HDEMO_SK" NUMBER, 
	"CS_BILL_ADDR_SK" NUMBER, 
	"CS_SHIP_CUSTOMER_SK" NUMBER, 
	"CS_SHIP_CDEMO_SK" NUMBER, 
	"CS_SHIP_HDEMO_SK" NUMBER, 
	"CS_SHIP_ADDR_SK" NUMBER, 
	"CS_CALL_CENTER_SK" NUMBER, 
	"CS_CATALOG_PAGE_SK" NUMBER, 
	"CS_SHIP_MODE_SK" NUMBER, 
	"CS_WAREHOUSE_SK" NUMBER, 
	"CS_ITEM_SK" NUMBER NOT NULL ENABLE, 
	"CS_PROMO_SK" NUMBER, 
	"CS_ORDER_NUMBER" NUMBER NOT NULL ENABLE, 
	"CS_QUANTITY" NUMBER, 
	"CS_WHOLESALE_COST" NUMBER(7,0), 
	"CS_LIST_PRICE" NUMBER(7,0), 
	"CS_SALES_PRICE" NUMBER(7,0), 
	"CS_EXT_DISCOUNT_AMT" NUMBER(7,0), 
	"CS_EXT_SALES_PRICE" NUMBER(7,0), 
	"CS_EXT_WHOLESALE_COST" NUMBER(7,0), 
	"CS_EXT_LIST_PRICE" NUMBER(7,0), 
	"CS_EXT_TAX" NUMBER(7,0), 
	"CS_COUPON_AMT" NUMBER(7,0), 
	"CS_EXT_SHIP_COST" NUMBER(7,0), 
	"CS_NET_PAID" NUMBER(7,0), 
	"CS_NET_PAID_INC_TAX" NUMBER(7,0), 
	"CS_NET_PAID_INC_SHIP" NUMBER(7,0), 
	"CS_NET_PAID_INC_SHIP_TAX" NUMBER(7,0), 
	"CS_NET_PROFIT" NUMBER(7,0)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."CUSTOMER" 
   (	"C_CUSTOMER_SK" NUMBER NOT NULL ENABLE, 
	"C_CUSTOMER_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"C_CURRENT_CDEMO_SK" NUMBER, 
	"C_CURRENT_HDEMO_SK" NUMBER, 
	"C_CURRENT_ADDR_SK" NUMBER, 
	"C_FIRST_SHIPTO_DATE_SK" NUMBER, 
	"C_FIRST_SALES_DATE_SK" NUMBER, 
	"C_SALUTATION" CHAR(10 BYTE), 
	"C_FIRST_NAME" VARCHAR2(50 BYTE), 
	"C_LAST_NAME" VARCHAR2(50 BYTE), 
	"C_PREFERRED_CUST_FLAG" CHAR(1 BYTE), 
	"C_BIRTH_DAY" NUMBER, 
	"C_BIRTH_MONTH" NUMBER, 
	"C_BIRTH_YEAR" NUMBER, 
	"C_BIRTH_COUNTRY" VARCHAR2(50 BYTE), 
	"C_LOGIN" CHAR(13 BYTE), 
	"C_EMAIL_ADDRESS" VARCHAR2(50 BYTE), 
	"C_LAST_REVIEW_DATE" CHAR(10 BYTE)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."CUSTOMER_ADDRESS" 
   (	"CA_ADDRESS_SK" NUMBER NOT NULL ENABLE, 
	"CA_ADDRESS_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"CA_STREET_NUMBER" CHAR(10 BYTE), 
	"CA_STREET_NAME" VARCHAR2(60 BYTE), 
	"CA_STREET_TYPE" CHAR(15 BYTE), 
	"CA_SUITE_NUMBER" CHAR(10 BYTE), 
	"CA_CITY" VARCHAR2(60 BYTE), 
	"CA_COUNTY" VARCHAR2(50 BYTE), 
	"CA_STATE" CHAR(2 BYTE), 
	"CA_ZIP" CHAR(10 BYTE), 
	"CA_COUNTRY" VARCHAR2(20 BYTE), 
	"CA_GMT_OFFSET" NUMBER(5,0), 
	"CA_LOCATION_TYPE" CHAR(20 BYTE)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."CUSTOMER_DEMOGRAPHICS" 
   (	"CD_DEMO_SK" NUMBER NOT NULL ENABLE, 
	"CD_GENDER" CHAR(1 BYTE), 
	"CD_MARITAL_STATUS" CHAR(1 BYTE), 
	"CD_EDUCATION_STATUS" CHAR(20 BYTE), 
	"CD_PURCHASE_ESTIMATE" NUMBER, 
	"CD_CREDIT_RATING" CHAR(10 BYTE), 
	"CD_DEP_COUNT" NUMBER, 
	"CD_DEP_EMPLOYED_COUNT" NUMBER, 
	"CD_DEP_COLLEGE_COUNT" NUMBER
   ) ;
 
CREATE TABLE "TPCDSLIKE"."DATE_DIM" 
   (	"D_DATE_SK" NUMBER NOT NULL ENABLE, 
	"D_DATE_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"D_DATE" DATE, 
	"D_MONTH_SEQ" NUMBER, 
	"D_WEEK_SEQ" NUMBER, 
	"D_QUARTER_SEQ" NUMBER, 
	"D_YEAR" NUMBER, 
	"D_DOW" NUMBER, 
	"D_MOY" NUMBER, 
	"D_DOM" NUMBER, 
	"D_QOY" NUMBER, 
	"D_FY_YEAR" NUMBER, 
	"D_FY_QUARTER_SEQ" NUMBER, 
	"D_FY_WEEK_SEQ" NUMBER, 
	"D_DAY_NAME" CHAR(9 BYTE), 
	"D_QUARTER_NAME" CHAR(6 BYTE), 
	"D_HOLIDAY" CHAR(1 BYTE), 
	"D_WEEKEND" CHAR(1 BYTE), 
	"D_FOLLOWING_HOLIDAY" CHAR(1 BYTE), 
	"D_FIRST_DOM" NUMBER, 
	"D_LAST_DOM" NUMBER, 
	"D_SAME_DAY_LY" NUMBER, 
	"D_SAME_DAY_LQ" NUMBER, 
	"D_CURRENT_DAY" CHAR(1 BYTE), 
	"D_CURRENT_WEEK" CHAR(1 BYTE), 
	"D_CURRENT_MONTH" CHAR(1 BYTE), 
	"D_CURRENT_QUARTER" CHAR(1 BYTE), 
	"D_CURRENT_YEAR" CHAR(1 BYTE)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."HOUSEHOLD_DEMOGRAPHICS" 
   (	"HD_DEMO_SK" NUMBER NOT NULL ENABLE, 
	"HD_INCOME_BAND_SK" NUMBER, 
	"HD_BUY_POTENTIAL" CHAR(15 BYTE), 
	"HD_DEP_COUNT" NUMBER, 
	"HD_VEHICLE_COUNT" NUMBER
   ) ;
 
CREATE TABLE "TPCDSLIKE"."INCOME_BAND" 
   (	"IB_INCOME_BAND_SK" NUMBER NOT NULL ENABLE, 
	"IB_LOWER_BOUND" NUMBER, 
	"IB_UPPER_BOUND" NUMBER
   ) ;
 
CREATE TABLE "TPCDSLIKE"."INVENTORY" 
   (	"INV_DATE_SK" NUMBER NOT NULL ENABLE, 
	"INV_ITEM_SK" NUMBER NOT NULL ENABLE, 
	"INV_WAREHOUSE_SK" NUMBER NOT NULL ENABLE, 
	"INV_QUANTITY_ON_HAND" NUMBER
   ) ;
 
CREATE TABLE "TPCDSLIKE"."ITEM" 
   (	"I_ITEM_SK" NUMBER NOT NULL ENABLE, 
	"I_ITEM_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"I_REC_START_DATE" DATE, 
	"I_REC_END_DATE" DATE, 
	"I_ITEM_DESC" VARCHAR2(200 BYTE), 
	"I_CURRENT_PRICE" NUMBER(7,0), 
	"I_WHOLESALE_COST" NUMBER(7,0), 
	"I_BRAND_ID" NUMBER, 
	"I_BRAND" CHAR(50 BYTE), 
	"I_CLASS_ID" NUMBER, 
	"I_CLASS" CHAR(50 BYTE), 
	"I_CATEGORY_ID" NUMBER, 
	"I_CATEGORY" CHAR(50 BYTE), 
	"I_MANUFACT_ID" NUMBER, 
	"I_MANUFACT" CHAR(50 BYTE), 
	"I_SIZE" CHAR(20 BYTE), 
	"I_FORMULATION" CHAR(20 BYTE), 
	"I_COLOR" CHAR(20 BYTE), 
	"I_UNITS" CHAR(10 BYTE), 
	"I_CONTAINER" CHAR(10 BYTE), 
	"I_MANAGER_ID" NUMBER, 
	"I_PRODUCT_NAME" CHAR(50 BYTE)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."PROMOTION" 
   (	"P_PROMO_SK" NUMBER NOT NULL ENABLE, 
	"P_PROMO_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"P_START_DATE_SK" NUMBER, 
	"P_END_DATE_SK" NUMBER, 
	"P_ITEM_SK" NUMBER, 
	"P_COST" NUMBER(15,0), 
	"P_RESPONSE_TARGET" NUMBER, 
	"P_PROMO_NAME" CHAR(50 BYTE), 
	"P_CHANNEL_DMAIL" CHAR(1 BYTE), 
	"P_CHANNEL_EMAIL" CHAR(1 BYTE), 
	"P_CHANNEL_CATALOG" CHAR(1 BYTE), 
	"P_CHANNEL_TV" CHAR(1 BYTE), 
	"P_CHANNEL_RADIO" CHAR(1 BYTE), 
	"P_CHANNEL_PRESS" CHAR(1 BYTE), 
	"P_CHANNEL_EVENT" CHAR(1 BYTE), 
	"P_CHANNEL_DEMO" CHAR(1 BYTE), 
	"P_CHANNEL_DETAILS" VARCHAR2(100 BYTE), 
	"P_PURPOSE" CHAR(15 BYTE), 
	"P_DISCOUNT_ACTIVE" CHAR(1 BYTE)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."REASON" 
   (	"R_REASON_SK" NUMBER NOT NULL ENABLE, 
	"R_REASON_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"R_REASON_DESC" CHAR(100 BYTE)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."SHIP_MODE" 
   (	"SM_SHIP_MODE_SK" NUMBER NOT NULL ENABLE, 
	"SM_SHIP_MODE_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"SM_TYPE" CHAR(30 BYTE), 
	"SM_CODE" CHAR(10 BYTE), 
	"SM_CARRIER" CHAR(20 BYTE), 
	"SM_CONTRACT" CHAR(20 BYTE)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."STORE" 
   (	"S_STORE_SK" NUMBER NOT NULL ENABLE, 
	"S_STORE_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"S_REC_START_DATE" DATE, 
	"S_REC_END_DATE" DATE, 
	"S_CLOSED_DATE_SK" NUMBER, 
	"S_STORE_NAME" VARCHAR2(50 BYTE), 
	"S_NUMBER_EMPLOYEES" NUMBER, 
	"S_FLOOR_SPACE" NUMBER, 
	"S_HOURS" CHAR(20 BYTE), 
	"S_MANAGER" VARCHAR2(40 BYTE), 
	"S_MARKET_ID" NUMBER, 
	"S_GEOGRAPHY_CLASS" VARCHAR2(100 BYTE), 
	"S_MARKET_DESC" VARCHAR2(100 BYTE), 
	"S_MARKET_MANAGER" VARCHAR2(40 BYTE), 
	"S_DIVISION_ID" NUMBER, 
	"S_DIVISION_NAME" VARCHAR2(50 BYTE), 
	"S_COMPANY_ID" NUMBER, 
	"S_COMPANY_NAME" VARCHAR2(50 BYTE), 
	"S_STREET_NUMBER" VARCHAR2(10 BYTE), 
	"S_STREET_NAME" VARCHAR2(60 BYTE), 
	"S_STREET_TYPE" CHAR(15 BYTE), 
	"S_SUITE_NUMBER" CHAR(10 BYTE), 
	"S_CITY" VARCHAR2(60 BYTE), 
	"S_COUNTY" VARCHAR2(40 BYTE), 
	"S_STATE" CHAR(2 BYTE), 
	"S_ZIP" CHAR(10 BYTE), 
	"S_COUNTRY" VARCHAR2(20 BYTE), 
	"S_GMT_OFFSET" NUMBER(5,0), 
	"S_TAX_PRECENTAGE" NUMBER(5,0)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."STORE_RETURNS" 
   (	"SR_RETURNED_DATE_SK" NUMBER, 
	"SR_RETURN_TIME_SK" NUMBER, 
	"SR_ITEM_SK" NUMBER NOT NULL ENABLE, 
	"SR_CUSTOMER_SK" NUMBER, 
	"SR_CDEMO_SK" NUMBER, 
	"SR_HDEMO_SK" NUMBER, 
	"SR_ADDR_SK" NUMBER, 
	"SR_STORE_SK" NUMBER, 
	"SR_REASON_SK" NUMBER, 
	"SR_TICKET_NUMBER" NUMBER NOT NULL ENABLE, 
	"SR_RETURN_QUANTITY" NUMBER, 
	"SR_RETURN_AMT" NUMBER(7,0), 
	"SR_RETURN_TAX" NUMBER(7,0), 
	"SR_RETURN_AMT_INC_TAX" NUMBER(7,0), 
	"SR_FEE" NUMBER(7,0), 
	"SR_RETURN_SHIP_COST" NUMBER(7,0), 
	"SR_REFUNDED_CASH" NUMBER(7,0), 
	"SR_REVERSED_CHARGE" NUMBER(7,0), 
	"SR_STORE_CREDIT" NUMBER(7,0), 
	"SR_NET_LOSS" NUMBER(7,0)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."STORE_SALES" 
   (	"SS_SOLD_DATE_SK" NUMBER, 
	"SS_SOLD_TIME_SK" NUMBER, 
	"SS_ITEM_SK" NUMBER NOT NULL ENABLE, 
	"SS_CUSTOMER_SK" NUMBER, 
	"SS_CDEMO_SK" NUMBER, 
	"SS_HDEMO_SK" NUMBER, 
	"SS_ADDR_SK" NUMBER, 
	"SS_STORE_SK" NUMBER, 
	"SS_PROMO_SK" NUMBER, 
	"SS_TICKET_NUMBER" NUMBER NOT NULL ENABLE, 
	"SS_QUANTITY" NUMBER, 
	"SS_WHOLESALE_COST" NUMBER(7,0), 
	"SS_LIST_PRICE" NUMBER(7,0), 
	"SS_SALES_PRICE" NUMBER(7,0), 
	"SS_EXT_DISCOUNT_AMT" NUMBER(7,0), 
	"SS_EXT_SALES_PRICE" NUMBER(7,0), 
	"SS_EXT_WHOLESALE_COST" NUMBER(7,0), 
	"SS_EXT_LIST_PRICE" NUMBER(7,0), 
	"SS_EXT_TAX" NUMBER(7,0), 
	"SS_COUPON_AMT" NUMBER(7,0), 
	"SS_NET_PAID" NUMBER(7,0), 
	"SS_NET_PAID_INC_TAX" NUMBER(7,0), 
	"SS_NET_PROFIT" NUMBER(7,0)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."TIME_DIM" 
   (	"T_TIME_SK" NUMBER NOT NULL ENABLE, 
	"T_TIME_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"T_TIME" NUMBER, 
	"T_HOUR" NUMBER, 
	"T_MINUTE" NUMBER, 
	"T_SECOND" NUMBER, 
	"T_AM_PM" CHAR(2 BYTE), 
	"T_SHIFT" CHAR(20 BYTE), 
	"T_SUB_SHIFT" CHAR(20 BYTE), 
	"T_MEAL_TIME" CHAR(20 BYTE)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."WAREHOUSE" 
   (	"W_WAREHOUSE_SK" NUMBER NOT NULL ENABLE, 
	"W_WAREHOUSE_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"W_WAREHOUSE_NAME" VARCHAR2(20 BYTE), 
	"W_WAREHOUSE_SQ_FT" NUMBER, 
	"W_STREET_NUMBER" CHAR(10 BYTE), 
	"W_STREET_NAME" VARCHAR2(60 BYTE), 
	"W_STREET_TYPE" CHAR(15 BYTE), 
	"W_SUITE_NUMBER" CHAR(10 BYTE), 
	"W_CITY" VARCHAR2(60 BYTE), 
	"W_COUNTY" VARCHAR2(50 BYTE), 
	"W_STATE" CHAR(2 BYTE), 
	"W_ZIP" CHAR(10 BYTE), 
	"W_COUNTRY" VARCHAR2(20 BYTE), 
	"W_GMT_OFFSET" NUMBER(5,0)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."WEB_PAGE" 
   (	"WP_WEB_PAGE_SK" NUMBER NOT NULL ENABLE, 
	"WP_WEB_PAGE_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"WP_REC_START_DATE" DATE, 
	"WP_REC_END_DATE" DATE, 
	"WP_CREATION_DATE_SK" NUMBER, 
	"WP_ACCESS_DATE_SK" NUMBER, 
	"WP_AUTOGEN_FLAG" CHAR(1 BYTE), 
	"WP_CUSTOMER_SK" NUMBER, 
	"WP_URL" VARCHAR2(100 BYTE), 
	"WP_TYPE" CHAR(50 BYTE), 
	"WP_CHAR_COUNT" NUMBER, 
	"WP_LINK_COUNT" NUMBER, 
	"WP_IMAGE_COUNT" NUMBER, 
	"WP_MAX_AD_COUNT" NUMBER
   ) ;
 
CREATE TABLE "TPCDSLIKE"."WEB_RETURNS" 
   (	"WR_RETURNED_DATE_SK" NUMBER, 
	"WR_RETURNED_TIME_SK" NUMBER, 
	"WR_ITEM_SK" NUMBER NOT NULL ENABLE, 
	"WR_REFUNDED_CUSTOMER_SK" NUMBER, 
	"WR_REFUNDED_CDEMO_SK" NUMBER, 
	"WR_REFUNDED_HDEMO_SK" NUMBER, 
	"WR_REFUNDED_ADDR_SK" NUMBER, 
	"WR_RETURNING_CUSTOMER_SK" NUMBER, 
	"WR_RETURNING_CDEMO_SK" NUMBER, 
	"WR_RETURNING_HDEMO_SK" NUMBER, 
	"WR_RETURNING_ADDR_SK" NUMBER, 
	"WR_WEB_PAGE_SK" NUMBER, 
	"WR_REASON_SK" NUMBER, 
	"WR_ORDER_NUMBER" NUMBER NOT NULL ENABLE, 
	"WR_RETURN_QUANTITY" NUMBER, 
	"WR_RETURN_AMT" NUMBER(7,0), 
	"WR_RETURN_TAX" NUMBER(7,0), 
	"WR_RETURN_AMT_INC_TAX" NUMBER(7,0), 
	"WR_FEE" NUMBER(7,0), 
	"WR_RETURN_SHIP_COST" NUMBER(7,0), 
	"WR_REFUNDED_CASH" NUMBER(7,0), 
	"WR_REVERSED_CHARGE" NUMBER(7,0), 
	"WR_ACCOUNT_CREDIT" NUMBER(7,0), 
	"WR_NET_LOSS" NUMBER(7,0)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."WEB_SALES" 
   (	"WS_SOLD_DATE_SK" NUMBER, 
	"WS_SOLD_TIME_SK" NUMBER, 
	"WS_SHIP_DATE_SK" NUMBER, 
	"WS_ITEM_SK" NUMBER NOT NULL ENABLE, 
	"WS_BILL_CUSTOMER_SK" NUMBER, 
	"WS_BILL_CDEMO_SK" NUMBER, 
	"WS_BILL_HDEMO_SK" NUMBER, 
	"WS_BILL_ADDR_SK" NUMBER, 
	"WS_SHIP_CUSTOMER_SK" NUMBER, 
	"WS_SHIP_CDEMO_SK" NUMBER, 
	"WS_SHIP_HDEMO_SK" NUMBER, 
	"WS_SHIP_ADDR_SK" NUMBER, 
	"WS_WEB_PAGE_SK" NUMBER, 
	"WS_WEB_SITE_SK" NUMBER, 
	"WS_SHIP_MODE_SK" NUMBER, 
	"WS_WAREHOUSE_SK" NUMBER, 
	"WS_PROMO_SK" NUMBER, 
	"WS_ORDER_NUMBER" NUMBER NOT NULL ENABLE, 
	"WS_QUANTITY" NUMBER, 
	"WS_WHOLESALE_COST" NUMBER(7,0), 
	"WS_LIST_PRICE" NUMBER(7,0), 
	"WS_SALES_PRICE" NUMBER(7,0), 
	"WS_EXT_DISCOUNT_AMT" NUMBER(7,0), 
	"WS_EXT_SALES_PRICE" NUMBER(7,0), 
	"WS_EXT_WHOLESALE_COST" NUMBER(7,0), 
	"WS_EXT_LIST_PRICE" NUMBER(7,0), 
	"WS_EXT_TAX" NUMBER(7,0), 
	"WS_COUPON_AMT" NUMBER(7,0), 
	"WS_EXT_SHIP_COST" NUMBER(7,0), 
	"WS_NET_PAID" NUMBER(7,0), 
	"WS_NET_PAID_INC_TAX" NUMBER(7,0), 
	"WS_NET_PAID_INC_SHIP" NUMBER(7,0), 
	"WS_NET_PAID_INC_SHIP_TAX" NUMBER(7,0), 
	"WS_NET_PROFIT" NUMBER(7,0)
   ) ;
 
CREATE TABLE "TPCDSLIKE"."WEB_SITE" 
   (	"WEB_SITE_SK" NUMBER NOT NULL ENABLE, 
	"WEB_SITE_ID" CHAR(16 BYTE) NOT NULL ENABLE, 
	"WEB_REC_START_DATE" DATE, 
	"WEB_REC_END_DATE" DATE, 
	"WEB_NAME" VARCHAR2(50 BYTE), 
	"WEB_OPEN_DATE_SK" NUMBER, 
	"WEB_CLOSE_DATE_SK" NUMBER, 
	"WEB_CLASS" VARCHAR2(50 BYTE), 
	"WEB_MANAGER" VARCHAR2(40 BYTE), 
	"WEB_MKT_ID" NUMBER, 
	"WEB_MKT_CLASS" VARCHAR2(50 BYTE), 
	"WEB_MKT_DESC" VARCHAR2(100 BYTE), 
	"WEB_MARKET_MANAGER" VARCHAR2(40 BYTE), 
	"WEB_COMPANY_ID" NUMBER, 
	"WEB_COMPANY_NAME" CHAR(50 BYTE), 
	"WEB_STREET_NUMBER" CHAR(10 BYTE), 
	"WEB_STREET_NAME" VARCHAR2(60 BYTE), 
	"WEB_STREET_TYPE" CHAR(15 BYTE), 
	"WEB_SUITE_NUMBER" CHAR(10 BYTE), 
	"WEB_CITY" VARCHAR2(60 BYTE), 
	"WEB_COUNTY" VARCHAR2(60 BYTE), 
	"WEB_STATE" CHAR(2 BYTE), 
	"WEB_ZIP" CHAR(10 BYTE), 
	"WEB_COUNTRY" VARCHAR2(20 BYTE), 
	"WEB_GMT_OFFSET" NUMBER(5,0), 
	"WEB_TAX_PERCENTAGE" NUMBER(5,0)
   ) ;
